export const MAP_CONFIG = {
  MAX_ZOOM: 8,
  IMAGE_WIDTH: 12288,
  IMAGE_HEIGHT: 6144,
  BLOCKS_PER_CRS_UNIT_AT_MAX_ZOOM: 64,
} as const;

export const TRANSPARENT_TILE_BASE64 =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGPQ19cHAAEeAI5OnbmSAAAAAElFTkSuQmCC=";
